name: "TMS Go Lint"
description: "Linting go code"
inputs:
  github-token:
    description: 'github token'
    required: true
  templ:
    description: 'Run templ build (optional)'
    required: false
    default: 'false'
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    
    - name: "setup private repo access"
      run: |
        export GOPRIVATE=github.com/TemoMailerSolutions/*
        git config --global url."https://${{ inputs.github-token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      shell: bash
      
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: "templ lint"
      if: ${{ inputs.templ == 'true' }}
      run: |
        templ_version=$(go list -m -f '{{.Version}}' github.com/a-h/templ)
        go install github.com/a-h/templ/cmd/templ@${templ_version}
        templ generate
      shell: bash
      
    - name: "go mod tidy"
      run: go mod tidy
      shell: bash
      
    - name: "install tooling"
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
      shell: bash
      
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.2
        args: --timeout 5m
      
    - name: govulncheck
      run: govulncheck ./...
      shell: bash
